name: "Docker Build and Push"

env:
  AWS_REGION: eu-west-1

on:
  workflow_run:
    workflows:
      - "Terraform"
    types:
      - completed

jobs:
  docker:
    name: "Docker Build and Push"
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: ecr_login
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ github.event.workflow_run.outputs.ecr_repository_url }}

      - name: Build Docker Image
        working-directory: ./server
        run: |
          docker build -t my-app:latest .

      - name: Tag Docker Image
        run: |
          docker tag my-app:latest ${{ github.event.workflow_run.outputs.ecr_repository_url }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ github.event.workflow_run.outputs.ecr_repository_url }}:latest
